networks:
  docker:
    ipam:
      config:
        - subnet: 192.19.0.0/24

services:
  go:
    build:
      context: .
      dockerfile: GoDockerfile
    ports:
      - 8080:8080
    container_name: web-go
    volumes:
      - /docker/go-study/pkg:/go/pkg
      - /docker/go-study/src/web:/go/src/web
    working_dir: /go/src/web
    command: bee run
